version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEBSERVER_PORT}:80
    depends_on:
      - php
  php:
    build: ./docker/php/
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - ../:/var/www/html
      - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini
    depends_on:
      - database
    restart: on-failure

  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/files:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: on-failure